name: Docker .NET Framework WPF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run the build process with Docker
      uses: addnab/docker-run-action@v3
      with:
          image: mcr.microsoft.com/dotnet/framework/sdk:4.8.1
          options: -v ${{ github.workspace }}:/var/workspace
          run: |
              msbuild dotnetframework-docker-cicd.sln -r -t:Rebuild -p:Configuration=$CONFIGURATION
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build results ${{ matrix.configuration }}
        path: bin/${{ matrix.configuration }}
