name: .NET Framework WPF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    container: 
      image: docker pull mcr.microsoft.com/dotnet/framework/sdk
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
