name: .NET Framework WPF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build
      run: msbuild dotnetframework-docker-cicd.sln -r -p:Configuration=${{ matrix.configuration }}
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build results
        path: bin/${{ matrix.configuration }}
